### ISSUE TITLE
Cannot get this to work for the life of me.

### ISSUE THREAD

**Issue by Soundtoxin** [Team-Fruit/SignPicture#13]
I tried imgur, mixtape.moe, the built-in uploader button. I can't get anything to work. Errors everywhere! Any idea what I'm doing wrong, or if it's a bug? I'm also using a different image every time.

Forge version: 2201
Sign Picture version: SignPicture-1.11.2-2.6.1-universal.jar
Modlist: http://sprunge.us/MXMF

![2016-12-30_05 20 45](https://cloud.githubusercontent.com/assets/3146494/21564206/834273f6-ce50-11e6-8d8f-f8d9bed9c7b5.png)
![2016-12-30_06 19 43](https://cloud.githubusercontent.com/assets/3146494/21564998/0330e6c2-ce58-11e6-8c28-794ab2b1ecce.png)

edit: After looking at the errors more, I'm wondering if this issue is perhaps the same as #10 

He is using Mac OS and I am using GNU/Linux. Could it be that this mod does something that only works properly on Windows?

**Comment by sjcl** [comment]
I think this problem is almost the same as #10 
However, we cooperated with acquaintances and tested the operation on Mac and Linux environments, but we could not find such a problem. Also, due to the nature of the language, problems due to OS differences are less likely to occur, so we believe there is another cause (URL processing etc).

**Comment by Soundtoxin** [comment]
My friend got on my server and was able to see the things I placed just fine, but I still can't see them. So the issue is definitely on my client. My friend is also on Windows, so that's one point toward my theory, IMO.

**Comment by Soundtoxin** [comment]
Have you guys found out anything more? Is there any more info I can try to gather for you? I would really love for this mod to work.

**Comment by Kamesuta** [comment]
I changed the creation of a temporary file from File.createTempFile () to my own implementation. I can not try it because the environment can not be reproduced. I am waiting for the impression of trying the alpha version.
[SignPicture-1.7.10-2.7.0.alpha-universal.zip](https://github.com/Team-Fruit/SignPicture/files/682091/SignPicture-1.7.10-2.7.0.alpha-universal.zip)

---
一時ファイルの作成をFile.createTempFile()から私の独自の実装に変更してみました。環境が再現できないので試すことができません。alpha版を試してみた感想をお待ちしております。

**Comment by Braggar** [comment]
That fixes the error for me.

**Comment by Kamesuta** [comment]
I am glad that the problem has been resolved. Close this thread.

**Comment by Soundtoxin** [comment]
Um, I am on 1.11.2. The alpha you released is only for 1.7.10. I will close this once I verify the issue is fixed for me.

**Comment by Soundtoxin** [comment]
Pardon my ignorance there, a friend pointed out I could just compile the 1.11.2 tree to test it. Did so and having some issues, though. For one, it seems to still not work, really. More majorly, with the addition of the newly compiled SignPictures, I get a fatal error trying to connect to my server! This doesn't happen in singleplayer, and of course SignPictures is not on my server in any form due to it being clientside, so this is pretty confusing.

![2017-01-03_07 56 01](https://cloud.githubusercontent.com/assets/3146494/21609816/2de58da2-d18a-11e6-8851-e734bf801bcc.png)
![2017-01-03_07 56 19](https://cloud.githubusercontent.com/assets/3146494/21609818/2de74840-d18a-11e6-8d2b-50d8ad9c62ce.png)

**Comment by sjcl** [comment]
Is the server log recorded? There should be details of the error that occurred when trying to connect.

**Comment by Soundtoxin** [comment]
latest.log: http://sprunge.us/AiMa
fml-server-latest.log: http://sprunge.us/KIgf

Hope this helps.

**Comment by Kamesuta** [comment]
The tree you compiled has not been modified yet. SignPicture is being developed mainly around 1.7.10. Thus, for branches that are not 1.7.10 (master), modifications will not be applied immediately.

The correspondence of 1.11.2 is now completed. Please try this alpha version.
[SignPicture-1.11.2-2.7.0.alpha-universal.zip](https://github.com/Team-Fruit/SignPicture/files/682462/SignPicture-1.11.2-2.7.0.alpha-universal.zip)

---
あなたがコンパイルしたツリーはまだ修正されていませんでした。SignPictureは、1.7.10を中心に開発を進めています。よって、1.7.10(master)ではないブランチはすぐには修正が適応されないでしょう。

今、1.11.2の対応が完了しました。このalpha版をお試しください。

**Comment by Soundtoxin** [comment]
![2017-01-03_09 09 48](https://cloud.githubusercontent.com/assets/3146494/21611885/6ac4597e-d194-11e6-9f30-67f21f996e33.png)
Still no luck, unfortunately.

Relevant part of client log: https://hastebin.com/asotupisoq.swift

**Comment by Kamesuta** [comment]
MaxRetryCountOver occurs when the number of failed reads exceeds the upper limit set in config. This is a specification that keeps repeating unnecessary retries many times. You can disable this function by setting MaxRetry to 0 from config.
You can solve this by right clicking on the signboard from GUI options and pressing Redownload from the displayed GUI and reloading it.

---
MaxRetryCountOverは読み込みに失敗した数がconfigで設定できる、上限の値を超えると発生します。これは無駄な再試行を何度も繰り返さないようにする仕様です。configよりMaxRetryを0にすることでこの機能を無効にすることができます。
GUIのoptionsより看板を右クリックし、表示されるGUIからRedownloadを押し、再読み込みすることで解決するでしょう。

**Comment by Soundtoxin** [comment]
Thank you for the info. I will edit my config accordingly.

**Comment by IlyaGreat** [comment]
Kamesutra, have same error on macOS Sierra. Minecraft 1.9.4
Please changed the creation for this version too.

**Comment by Kamesuta** [comment]
Ok, I'll release a new version soon
